name: PR checks

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Set up uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          enable-cache: true
      - name: Set up linters
        run: |
          if ! make -j setup-lint; then
            sudo apt-get update
            make -j setup-lint
          fi
      - name: Lint
        run: make -k lint

  test:
    name: Test (Python ${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14", "3.15"]
    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Set up uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}
      - name: Set up test environment
        run: make setup-tests
      - name: Test
        run: make test

  test-distros:
    name: Test (${{ matrix.distro }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - almalinux/9
          - centos/9-Stream
          - debian/forky
          - debian/sid
          - devuan/chimaera
          - devuan/daedalus
          - devuan/excalibur
          - fedora/43
          - kali
          - mint/21.3
          - mint/zena
    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Set up LXD
        uses: canonical/setup-lxd@v1
      - name: Run tests in container
        run: make test-lxd LXD_DISTRO=${{ matrix.distro }}
